name: Images legacy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
      - v1.9
      - pr/test-docker-images-legacy
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

jobs:
  multi-registries:
    if: github.repository == 'cilium/cilium'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::pr-test-docker-images-legacy
      - name: Build Cilium Operator Generic
        id: docker_build_operator_generic
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cilium-operator-generic.Dockerfile
          push: true
          cache-from: ${{ github.repository_owner }}/operator-generic-dev:cache-build-${{ steps.vars.outputs.tag }}
          cache-to: mode=max,type=registry,ref=${{ github.repository_owner }}/operator-generic-dev:cache-build-${{ steps.vars.outputs.tag }}
          tags: |
            ${{ github.repository_owner }}/operator-generic-dev:${{ github.sha }}
            ${{ github.repository_owner }}/operator-generic-dev:${{ steps.vars.outputs.tag }}
            quay.io/${{ github.repository_owner }}/operator-generic-dev:${{ github.sha }}
            quay.io/${{ github.repository_owner }}/operator-generic-dev:${{ steps.vars.outputs.tag }}
      - name: Image digests
        run: |
          echo "::group::Image digests"
          echo "Official Docker Image Repositories: docker.io, quay.io"
          echo "Cilium Operator Generic: ${{ steps.docker_build_operator_generic.outputs.digest }}"
          echo "::endgroup::"
